// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe91wj8h2IFrEGN9L8yHU5HHCM8ry5Lco',
    appId: '1:911533659407:web:7655960085085ca6cb9a7a',
    messagingSenderId: '911533659407',
    projectId: 'cargointernapp',
    authDomain: 'cargointernapp.firebaseapp.com',
    storageBucket: 'cargointernapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNI06DCwbBzbWvqU9geNW9TJp9U4d9jZQ',
    appId: '1:911533659407:android:6847de80d08334fecb9a7a',
    messagingSenderId: '911533659407',
    projectId: 'cargointernapp',
    storageBucket: 'cargointernapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvW-r0DMkqvSwXCIErKUcHgTW0cMUBdo',
    appId: '1:911533659407:ios:90602c4926ec7a85cb9a7a',
    messagingSenderId: '911533659407',
    projectId: 'cargointernapp',
    storageBucket: 'cargointernapp.firebasestorage.app',
    iosBundleId: 'com.example.cargoInternApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvW-r0DMkqvSwXCIErKUcHgTW0cMUBdo',
    appId: '1:911533659407:ios:90602c4926ec7a85cb9a7a',
    messagingSenderId: '911533659407',
    projectId: 'cargointernapp',
    storageBucket: 'cargointernapp.firebasestorage.app',
    iosBundleId: 'com.example.cargoInternApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe91wj8h2IFrEGN9L8yHU5HHCM8ry5Lco',
    appId: '1:911533659407:web:8427f325628b132ecb9a7a',
    messagingSenderId: '911533659407',
    projectId: 'cargointernapp',
    authDomain: 'cargointernapp.firebaseapp.com',
    storageBucket: 'cargointernapp.firebasestorage.app',
  );
}
